#!/bin/bash

# Set virtual memory limit to 1G
ulimit -v 1000000

# Temporary output file
tmp="${3}_tmp"

# Call planner
#timeout 10 "$(dirname "$0")"/siw-then-bfsf --domain $1 --problem $2 --output $3
timeout 10 "$(dirname "$0")"/MpC -Q -o $3 -m 500 -P 1 $1 $2

# Format output
awk '{print toupper(substr($0, index($0,$3)))}' $3 > $tmp && mv $tmp $3
